### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by pmjdebruijn**
The commits are small and mostly speak for themselves :)

### CODE REVIEW

**Comment by ftoledo** [comment]
please merge
i can not build
```
ragnarok@ragnarok:~/src/ragnarok/ipxnet$ make
g++ -Wall  main.cpp ipxserver.cpp -lSDL_net -o ipxnet
ipxserver.cpp: In function ‘void ackClient(IPaddress)’:
ipxserver.cpp:118:8: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
   Bits result;
        ^~~~~~
/usr/bin/ld: /tmp/cc3HWV3Q.o: referencia sin definir al símbolo 'SDL_GetError'
//usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:9: fallo en las instrucciones para el objetivo 'ipxnet'
make: *** [ipxnet] Error 1

```

**Comment by Neo-Desktop** [comment]
@intangir any possibility of reviewing and merging this?

**Comment by intangir** [comment]
i don't use or maintain this code anymore

feel free to maintain your own fork, haven't touched it in like a decade

**Comment by Neo-Desktop** [comment]
> i don't use or maintain this code anymore
> 
> feel free to maintain your own fork, haven't touched it in like a decade

Sounds good. The Vogons / Dosbox Wiki needs to reflect this. Can we get you to "archive" this repository in the settings?

**Comment by intangir** [comment]
finally tested/merged this, thanks for the fixes

**Pull request merged**
